---
apiVersion: v1
kind: Service
metadata:
  name: alpha
  labels:
    app: alpha
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: alpha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
  labels:
    app: alpha
spec:
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
    spec:
      containers:
      - name: alpha
        image: alpha
